version: "3.3"
networks:
    monitor:
        driver: bridge
services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: "node-exporter0"
    ports:
      - "9130:9100"
    restart: always
    networks:
      - monitor
  
  cadvisor:
    image: google/cadvisor:latest
    container_name: "cadvisor0"
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8081:8080"
    networks:
      - monitor

  prometheus:
    image: prom/prometheus:latest
    container_name: "prometheus0"
    restart: always
    ports:
      - "9097:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./prometheus_data:/prometheus"
    networks:
      - monitor

  grafana:
    image: grafana/grafana
    container_name: "grafana0"
    ports:
      - "3005:3000"
    restart: always
    volumes:
      - "./grafana_data:/var/lib/grafana"
      - "./grafana_log:/var/log/grafana"
      - "./grafana_data/crypto_data:/crypto_data"  # 宿主机的地址是冒号前面的，冒号后面的是容器地址，不可变，这个用来放sqlite数据库的位置。
    networks:
      - monitor

